Improved/fixed/clarified CI test reports upload script generation
-Improved comments of report history generation
-Simplified creation of directories
-Noted limitations
-Fixed test reports history gathering when there are already some for the current branch
-Unified way to get SDK version in order to avoid delta between git describe in docker container and the git describe of the machine in charge of uploads

diff --git a/.gitlab-ci-files/job-uploads.yml b/.gitlab-ci-files/job-uploads.yml
--- a/.gitlab-ci-files/job-uploads.yml
+++ b/.gitlab-ci-files/job-uploads.yml
@@ -442,22 +442,32 @@ job-xamarin-upload:
     - LIME_VERSION=$(git -C lime describe)
     - LIBLINPHONE_VERSION=$(git -C liblinphone describe)
     - MS2_VERSION=$(git -C mediastreamer2 describe)
-    - SDK_VERSION=$(git describe)
+
+    #We get the SDK version from earlier jobs instead of using git describe so the URL generated in the tester job will be the same in the upload job, no matter the platform used and the git version delta
+    - SDK_VERSION=$(cat ${CI_PROJECT_DIR}/build-desktop/gitdescribe.txt)
+    - echo $SDK_VERSION
+    - git describe
+
     - BRANCH=$CI_COMMIT_REF_NAME
     - ESCAPED_BRANCH=$(echo $BRANCH | tr / _)
+    - echo $ESCAPED_BRANCH
     - PARENT_BRANCH=$(echo $(git log --pretty=oneline  --pretty=format:%D -n 1 HEAD~1 | awk -F ", " '{print $1}' | awk -F "origin/" '{print $2}'))
     - echo $(git log --pretty=oneline  --pretty=format:%D -n 1 HEAD~1)
     - echo $(git log --pretty=oneline  --pretty=format:%D -n 1 HEAD~1 | awk -F ", " '{print $1}')
     - echo $(git log --pretty=oneline  --pretty=format:%D -n 1 HEAD~1 | awk -F ", " '{print $1}' | awk -F "origin/" '{print $2}')
+    - echo $PARENT_BRANCH
     - |
         if [[ -z $ESCAPED_BRANCH ]];
         then ESCAPED_BRANCH=master
         fi
+    - echo $ESCAPED_BRANCH
     - |
-        if [[ $ESCAPED_BRANCH=master ]];
+        if [[ $ESCAPED_BRANCH == master ]];
         then PARENT_BRANCH=master
         fi
-
+    - echo $ESCAPED_BRANCH
+    - echo $PARENT_BRANCH
+    - PARENT_BRANCH=$(echo $PARENT_BRANCH | tr / _)
     - echo $PARENT_BRANCH
     - cd results
 
@@ -492,78 +502,68 @@ job-xamarin-upload:
     - echo "#!/bin/bash" | tee -a allure_launch_script
 
     #we use as a folder the name of the branch with the slashes replaced by underscores (ex feature/random -> feature_random)
-    #navigation to the branch folder and creation if it doesn't exists
-    - echo "if [[ -n \$(find -maxdepth 1 -name $ESCAPED_BRANCH) ]];" | tee -a allure_launch_script
-    - echo "  then cd $ESCAPED_BRANCH  || exit 1; else mkdir $ESCAPED_BRANCH && cd $ESCAPED_BRANCH || exit 1;" | tee -a allure_launch_script
-    - echo "fi || true" | tee -a allure_launch_script
+    #creation if it doesn't exists
+    - echo "mkdir -p $ESCAPED_BRANCH || exit 1;" | tee -a allure_launch_script
 
     #as a subfoldder name, we use the git describe of the sdk (version + commit hash)
-    #no need to search for an history in the case of a retry (if the directory related to the commit already exists)
-    - echo FIND_DIR="\$(find -path './$SDK_VERSION*/$PLATFORM/$TESTER')" | tee -a allure_launch_script
+    #we search for a report associated to a commit directory
+    # * is used to search for new name (COMMIT-JOB_ID) and old name (COMMIT)
+    #We enter in the if in case of a retry/commit --amend
+    - echo FIND_DIR="\$(find \$(pwd) -maxdepth 2 -name '*/$ESCAPED_BRANCH/$SDK_VERSION*')" | tee -a allure_launch_script
     - echo "if [[ -n \$FIND_DIR ]];" | tee -a allure_launch_script
-    - echo "  then cd \$(echo \$FIND_DIR | head -n 1) || exit 1;" | tee -a allure_launch_script
-    #ugly workaround while we are using cd to reuse the rest of the script without rewriting it
-    - echo "  cd ../.. || exit 1;" | tee -a allure_launch_script
-    - echo " CREATED_COMMIT_REF_FOLDER=\"NO\"" | tee -a allure_launch_script
+    - echo "  then TEST_WORKSPACE_LOCATION=$(echo $FIND_DIR | sort -r | head -n 1) || exit 1;" | tee -a allure_launch_script
+    - echo "  CREATED_COMMIT_REF_FOLDER=\"NO\"" | tee -a allure_launch_script
     - echo "else" | tee -a allure_launch_script
-    - echo " LAST_MODIFIED_FOLDER=\$(ls -ct | head -n1)" | tee -a allure_launch_script
-    - echo " mkdir $SDK_VERSION-$TEST_REPORT_ID && cd $SDK_VERSION-$TEST_REPORT_ID || exit 1 ;" | tee -a allure_launch_script
-    - echo " CREATED_COMMIT_REF_FOLDER=\"YES\"" | tee -a allure_launch_script
+
+    - echo "  TEST_WORKSPACE_LOCATION=\$(pwd)/$ESCAPED_BRANCH/$SDK_VERSION-$TEST_REPORT_ID/$PLATFORM/$TESTER|| exit 1;" | tee -a allure_launch_script
+
+
+    - echo "  CREATED_COMMIT_REF_FOLDER=\"YES\"" | tee -a allure_launch_script
     - echo "fi" | tee -a allure_launch_script
-    - echo "if [[ -n \$(ls | grep $PLATFORM) ]];" | tee -a allure_launch_script
-    - echo "  then cd $PLATFORM || exit 1" | tee -a allure_launch_script
-    - echo "else" | tee -a allure_launch_script
-    - echo "  mkdir $PLATFORM && cd $PLATFORM || exit 1" | tee -a allure_launch_script
-    - echo "fi" | tee -a allure_launch_script
-    - echo "if [[ -n \$(ls | grep $TESTER) ]];" | tee -a allure_launch_script
-    - echo "  then cd $TESTER || exit 1" | tee -a allure_launch_script
-    - echo "else" | tee -a allure_launch_script
-    - echo "  mkdir $TESTER && cd $TESTER || exit 1"| tee -a allure_launch_script
-    - echo "fi" | tee -a allure_launch_script
+
+    - echo "mkdir -p \$TEST_WORKSPACE_LOCATION || exit 1" | tee -a allure_launch_script
 
     #Not currently needed
-    #- echo "cp ../../../../categories.json categories.json;" | tee -a allure_launch_script
 
-    #The LAST_MODIFIED_FOLDER variable will help us to save the latest tests history before deletion and move it
+    #The LAST_MODIFIED_PATH variable will help us to save the latest tests history before deletion and move it (for a same given branch)
     #in the new folder, to be used by the new allure report generation
 
-    #need to copy the history from parent branch if there is no previous test reports in current branch (if there is no LAST_MODIFIED_FOLDER)
+    #need to copy the history from parent branch if there is no previous test reports in current branch (if there is no LAST_MODIFIED_PATh)
     #current branch = ESCAPED_BRANCH
 
     #workaround in case the PARENT_BRANCH check fails (to allow the script to run even if PARENT_BRANCH is empty)
     - echo "PARENT_BRANCH=\$(echo '$PARENT_BRANCH')" | tee -a allure_launch_script
-    - echo "if [[ \$CREATED_COMMIT_REF_FOLDER = \"YES\" && -z \$LAST_MODIFIED_FOLDER && -n \$PARENT_BRANCH ]];" | tee -a allure_launch_script
-    - echo "  then" | tee -a allure_launch_script
-    - echo "  cd ../../../../\$PARENT_BRANCH || exit 1" | tee -a allure_launch_script
-    - echo "  LAST_MODIFIED_PATH=\$(find -O3 -path '*/$PLATFORM/$TESTER/allure-report/history' | tac | head -n 1)" | tee -a allure_launch_script
-    - echo "  cd ../$ESCAPED_BRANCH/$SDK_VERSION-$TEST_REPORT_ID/$PLATFORM/$TESTER || exit 1" | tee -a allure_launch_script
-    - echo "  cp -r ../../../../\$PARENT_BRANCH/\$LAST_MODIFIED_PATH history;" | tee -a allure_launch_script
+    - echo "if [[ \$CREATED_COMMIT_REF_FOLDER = \"YES\" && -n \$PARENT_BRANCH ]];" | tee -a allure_launch_script
+    - echo "then" | tee -a allure_launch_script
+    #LIMITATION : no guarantee that find orders the paths by creation date
+    - echo "  LAST_MODIFIED_PATH=\$(find \$(pwd)/$PARENT_BRANCH -path "*/$PLATFORM/$TESTER/allure-report/history" | tac | head -n 1)" | tee -a allure_launch_script
+    - echo "  cp -r \$LAST_MODIFIED_PATH \$(pwd)/$ESCAPED_BRANCH/$SDK_VERSION-$TEST_REPORT_ID/$PLATFORM/$TESTER/history;" | tee -a allure_launch_script
     - echo "else" | tee -a allure_launch_script
-    - echo "  cp -r \$(find -O3 ../../../ -path '*/$PLATFORM/$TESTER/allure-report/history' | tac | head -n 1) history;" | tee -a allure_launch_script
+    - echo "  cp -r \$(find \$(pwd) -path '*/$ESCAPED_BRANCH/*/$PLATFORM/$TESTER/allure-report/history' | tac | head -n 1) \$TEST_WORKSPACE_LOCATION/history;" | tee -a allure_launch_script
     - echo "fi;" | tee -a allure_launch_script
 
 
     #we move the BCUnit report and environment.properties to the desired folder to prepare allure report generation
-    - echo "mv ../../../../environment.properties . && mv ../../../../$XML_FILENAME_START_PATTERN* ." | tee -a allure_launch_script
+    - echo "mv \$(pwd)/environment.properties \$TEST_WORKSPACE_LOCATION && mv \$(pwd)/$XML_FILENAME_START_PATTERN* \$TEST_WORKSPACE_LOCATION" | tee -a allure_launch_script
 
     #symlink with username to ease searching
-    - echo "mkdir -p ../../../$GITLAB_USER_LOGIN/$SDK_VERSION-$TEST_REPORT_ID/$PLATFORM" | tee -a allure_launch_script
-    - echo "ln -s \$(pwd) ../../../$GITLAB_USER_LOGIN/$SDK_VERSION-$TEST_REPORT_ID/$PLATFORM/$TESTER" | tee -a allure_launch_script
+    - echo "mkdir -p \$(pwd)/$ESCAPED_BRANCH/$GITLAB_USER_LOGIN/$SDK_VERSION-$TEST_REPORT_ID/$PLATFORM" | tee -a allure_launch_script
+    - echo "ln -s \$TEST_WORKSPACE_LOCATION \$(pwd)/$ESCAPED_BRANCH/$GITLAB_USER_LOGIN/$SDK_VERSION-$TEST_REPORT_ID/$PLATFORM" | tee -a allure_launch_script
 
     #we use the uploaded version of allure on parent directory because the allure version in repos is too old (TO DO auto install new version properly)
-    - echo "~/allure-2.10.0/bin/allure generate --clean ." | tee -a allure_launch_script
+    - echo "~/allure-2.10.0/bin/allure generate --clean \$TEST_WORKSPACE_LOCATION -o \$TEST_WORKSPACE_LOCATION/allure-report" | tee -a allure_launch_script
 
     #we now remove the history directory
     - echo "pwd" | tee -a allure_launch_script
     - cat allure_launch_script
     - echo "ls -lah" | tee -a allure_launch_script
-    - echo "du -h ." | tee -a allure_launch_script
+    - echo "du -h \$TEST_WORKSPACE_LOCATION" | tee -a allure_launch_script
 
-    - echo "rm -r history || echo 'deletion of temp history failed. History could not be gathered ?'" | tee -a allure_launch_script
+    - echo "rm -r \$TEST_WORKSPACE_LOCATION/history || echo 'deletion of temp history failed. History could not be gathered ?'" | tee -a allure_launch_script
     - cat allure_launch_script
 
     #the average size of a report is around 13Mio
-    - echo "du -h ." | tee -a allure_launch_script
+    - echo "du -h \$TEST_WORKSPACE_LOCATION" | tee -a allure_launch_script
     - cat allure_launch_script
 
     - chmod u+x allure_launch_script
@@ -577,6 +577,7 @@ job-xamarin-upload:
     - ssh $DEPLOY_SERVER "cd $DEPLOY_TESTS_DIRECTORY || exit 1 && bash -x allure_launch_script"
 
     #TODO think about deletion of oldest reports, or compression
+    #It is done by a CRON job on the target machine
 
     #categories.json is usefull to define the pattern of the tests states.
     #ex
