Automate process of recloning repository in case ot a bad config file on Windows. This is basically repairCorruption.bat but in CI

diff --git a/.gitlab-ci-files/job-windows.yml b/.gitlab-ci-files/job-windows.yml
--- a/.gitlab-ci-files/job-windows.yml
+++ b/.gitlab-ci-files/job-windows.yml
@@ -36,8 +36,51 @@
 #  variables:
 #    CMAKE_OPTIONS: -DENABLE_VIDEO=NO
 #  extends: job-windows-vs2015
-.job-windows-vs2017:
+.after_script_build-windows:
   extends: .job-prepare
+  after_script:
+    - dir
+    - git remote prune origin && git fetch --prune
+    - git fsck --progress > .git-test-corruption.txt 2>&1
+    - type .git-test-corruption.txt
+    - git submodule foreach --recursive "git remote prune origin && git fetch --prune"
+    #We need to use powershell here because CMD doesn't know how to handle git submodule subshells...
+    - |
+      powershell -command "git submodule foreach --recursive 'git fsck --progress >> $toplevel/.git-test-corruption.txt 2>&1'"
+    - dir bctoolbox
+    - type .git-test-corruption.txt
+    - set exit=0
+    # || cd. is the windows equivalent of || true
+    - 'FINDSTR /c:"fatal: bad config line" .git-test-corruption.txt || echo errorlevel=%ERRORLEVEL% ||  cd.'
+    - echo errorlevel=%ERRORLEVEL%
+    - |
+      IF %ERRORLEVEL% NEQ 0 GOTO :END
+      echo Git corruption detected : Repairing.
+      for %%I in (.) do set folder=%%~nxI
+      cd ..
+      RMDIR /S /Q %folder%
+      echo Cloning repository.
+      git clone git@gitlab.linphone.org:BC/public/%folder%.git --recursive
+      cd %folder% && echo Repository cloned. || echo Repository clone failed && set exit=1 && GOTO :END
+      git fsck --progress > .git-test-corruption.txt 2>&1
+      'FINDSTR /c:"fatal: bad config line" .git-test-corruption.txt || echo errorlevel=%ERRORLEVEL% || cd.'
+      echo errorlevel=%ERRORLEVEL%
+      IF %ERRORLEVEL% NEQ 0 GOTO :END
+      echo Cannot repair the local repository. Please check it manually
+      set exit=1
+      :END
+      IF EXIST .git-test-corruption.txt DEL .git-test-corruption.txt
+
+    - echo %EXIT%;
+    - exit %EXIT%;
+  artifacts:
+    paths:
+      - build-desktop\linphone-sdk\*
+    when: always
+    expire_in: 1 week
+
+.job-windows-vs2017:
+  extends: .after_script_build-windows
   stage: build
   tags: [ "windows" ]
   except:
@@ -57,7 +100,7 @@
     - set PATH_TEMP=%PATH_TEMP:C:\Strawberry\c\bin;=%
     - set PATH=%PATH_TEMP%;C:\msys64;C:\msys64\usr\bin;C:\msys64\%MINGW_TYPE%\bin
     #handling the case of previous job cancellation
-    - IF "%MINGW_TYPE%"=="mingw64" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat") ELSE (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat")    
+    - IF "%MINGW_TYPE%"=="mingw64" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat") ELSE (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat")
     - IF EXIST build-desktop RMDIR /S /Q build-desktop
     - mkdir build-desktop
     - cd build-desktop
@@ -75,14 +118,9 @@
     - mkdir %OUTPUT_ZIP_FOLDER%
     - copy /B *.zip "%CI_PROJECT_DIR%/build-desktop/linphone-sdk/%OUTPUT_ZIP_FOLDER%"
 ################
-  artifacts:
-    paths:
-      - build-desktop\linphone-sdk\*
-    when: always
-    expire_in: 1 week
 
 .job-windows-vs2017-ninja:
-  extends: .job-prepare
+  extends: .after_script_build-windows
   stage: build
   tags: [ "windows" ]
   except:
@@ -147,7 +185,7 @@
 ######################################################
 # JOBS
 ######################################################
-    
+
 job-windows-vs2017-ninja-win64:
   extends: .job-windows-vs2017-ninja
   variables:
@@ -238,7 +276,7 @@ job-windows-vs2017-win32-novideo:
     - set PATH_TEMP=%PATH_TEMP:C:\Program Files\NASM=%
     - set PATH_TEMP=%PATH_TEMP:C:\Strawberry\c\bin;=%
     - set PATH=%PATH_TEMP%;C:\msys64;C:\msys64\usr\bin;C:\msys64\%MINGW_TYPE%\bin
-    - IF "%MINGW_TYPE%"=="mingw64" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat") ELSE (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat")    
+    - IF "%MINGW_TYPE%"=="mingw64" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat") ELSE (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat")
     - cd %CI_PROJECT_DIR%/build-desktop/linphone-sdk/desktop/
 
     #windows doesn't understand the meaning of the slash to launch an executable in basic command prompt
@@ -306,7 +344,7 @@ test-linphone-windows-win32-ninja:
       - $ENABLE_WINDOWS_TESTS_WIN32_NINJA
   needs:
     - job-windows-vs2017-ninja-win32
-    
+
 test-linphone-windows-win64-ninja:
   extends: .test-linphone-windows
   only:
