Commented unneeded tests to check packaging, list files generated by build to set right artifacts [ci skip]

diff --git a/.gitlab-ci-files/job-android.yml b/.gitlab-ci-files/job-android.yml
--- a/.gitlab-ci-files/job-android.yml
+++ b/.gitlab-ci-files/job-android.yml
@@ -18,6 +18,8 @@
     - echo $CMAKE_OPTIONS
     - cmake .. -G "$CMAKE_GENERATOR" -DLINPHONESDK_PLATFORM=Android -DLINPHONESDK_ANDROID_ARCHS="$ANDROID_ARCHS" $DEFAULT_LINUX_CMAKE_OPTIONS $CMAKE_OPTIONS $SCHEDULE_CMAKE_OPTIONS $CMAKE_SANITIZER_OPTIONS
     - cmake --build . --target sdk -- $ADDITIONAL_BUILD_OPTIONS
+    - ls -la
+    - tree
 
   artifacts:
     paths:
@@ -27,6 +29,9 @@
       #Needed for tester
       - build/libs-debug/*
       - linphone/tester/*
+
+      #Needed of uploads
+      - build/build.gradle
     when: always
     expire_in: 1 week
 
@@ -155,63 +160,66 @@ job-android-ninja-r20:
 #    CMAKE_SANITIZER_OPTIONS: -DENABLE_SANITIZER=YES
 #  extends: job-android-ninja-r20
 
+#################################################
+# Tests Android
+#################################################
 
-test-android-r17c:
-  tags: [ "docker-android-test-r17c" ]
-  stage: test
-  allow_failure: true
-  dependencies:
-    - job-android-makefile-r17c
-  only:
-    variables:
-      - $NIGHTLY_MASTER
-  script:
-    - cd ${CI_PROJECT_DIR}/tester/Android
+#test-android-r17c:
+#  tags: [ "docker-android-test-r17c" ]
+#  stage: test
+#  allow_failure: true
+#  dependencies:
+#    - job-android-makefile-r17c
+#  only:
+#    variables:
+#      - $NIGHTLY_MASTER
+#  script:
+#    - cd ${CI_PROJECT_DIR}/tester/Android
     # uninstalling tester apps on device to prevent conflicts, but running anyway if there isn't some found.
-    - adb uninstall org.linphone.tester.test || true
-    - adb uninstall org.linphone.tester || true
+#    - adb uninstall org.linphone.tester.test || true
+#    - adb uninstall org.linphone.tester || true
 
     # build of the testers
-    - ./gradlew assembleDebug
-    - ./gradlew assembleDebugAndroidTest
+#    - ./gradlew assembleDebug
+#    - ./gradlew assembleDebugAndroidTest
 
     # gathering full trace of logcat in case of a coredump
-    - |
-        for x in `adb devices | sed -n '1!p' | sed '/^$/d' | awk '{print $1;}'`; do
-        adb -s $x logcat -c
-        adb -s $x logcat -v time > $x.txt &
-        echo $! > $x.pid
-        done
+#    - |
+#        for x in `adb devices | sed -n '1!p' | sed '/^$/d' | awk '{print $1;}'`; do
+#        adb -s $x logcat -c
+#        adb -s $x logcat -v time > $x.txt &
+#        echo $! > $x.pid
+#        done
 
     # Test launching
-    - |
-        java -jar ~/spoon.jar --output spoon --apk app/build/outputs/apk/debug/app-debug.apk \
-        --test-apk app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
-        --class-name 'org.linphone.tester.AllTests' \
-        --fail-on-failure --fail-if-no-device-connected --grant-all || ( if [ $? -ne 0 ]
-        then
-        echo "Some tests are failed" && false
-        fi)
+#    - |
+#        java -jar ~/spoon.jar --output spoon --apk app/build/outputs/apk/debug/app-debug.apk \
+#        --test-apk app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
+#        --class-name 'org.linphone.tester.AllTests' \
+#        --fail-on-failure --fail-if-no-device-connected --grant-all || ( if [ $? -ne 0 ]
+#        then
+#        echo "Some tests are failed" && false
+#        fi)
 
-  after_script:
+#  after_script:
     #putting all the trace in the ndk stack txt file
-    - |
-        for x in `adb devices | sed -n '1!p' | sed '/^$/d' | awk '{print $1;}'`; do
-        cat tester/Android/$x.txt | ndk-stack -sym build/libs-debug/`adb -s $x shell getprop ro.product.cpu.abi | tr -d '\r'` > tester/Android/$x-ndk-stack.txt
-        done
+#    - |
+#        for x in `adb devices | sed -n '1!p' | sed '/^$/d' | awk '{print $1;}'`; do
+#        cat tester/Android/$x.txt | ndk-stack -sym build/libs-debug/`adb -s $x shell getprop ro.product.cpu.abi | tr -d '\r'` > tester/Android/$x-ndk-stack.txt
+#        done
     #debugging output to see why the tests are failing in runner
-    - cat tester/Android/$x.txt
-    - tar zcvf tester/Android/logs-tests-android.tar.gz tester/Android/spoon/ tester/Android/*.txt
+#    - cat tester/Android/$x.txt
+#    - tar zcvf tester/Android/logs-tests-android.tar.gz tester/Android/spoon/ tester/Android/*.txt
 
     #Gathering artifacts in one folder to ease their use
-    - sudo mkdir ${CI_PROJECT_DIR}/results
-    - sudo chmod 777 ${CI_PROJECT_DIR}/results
-    - mv tester/Android/logs-tests-android.tar.gz ${CI_PROJECT_DIR}/results
-    - mv tester/Android/spoon/junit-reports/*.xml ${CI_PROJECT_DIR}/results
+#    - sudo mkdir ${CI_PROJECT_DIR}/results
+#    - sudo chmod 777 ${CI_PROJECT_DIR}/results
+#    - mv tester/Android/logs-tests-android.tar.gz ${CI_PROJECT_DIR}/results
+#    - mv tester/Android/spoon/junit-reports/*.xml ${CI_PROJECT_DIR}/results
 
-  artifacts:
-    paths:
-      - results/*
+#  artifacts:
+#    paths:
+#      - results/*
 
-    when: always
-    expire_in: 4 week
+#    when: always
+#    expire_in: 4 week
